version: '3.9'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    volumes:
      - "./server:/app"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
